version: "3.9"

services:
  php-fpm:
    build:
      context: ./api
    restart: unless-stopped
    depends_on:
      - database
    working_dir: /var/www
    environment:
      APP_ENV: dev
      MERCURE_URL: http://localhost
      MERCURE_PUBLIC_URL: http://localhost
      MERCURE_JWT_SECRET: 8gQ7}q\q8DE%Z>nv
      #JWT_SECRET_KEY: 2m2R7}q\qGq38gQ
    volumes:
      - ./api:/var/www:rw,cached
      - ./api/docker/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      #- ./api:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - php-fpm
      - site
      - admin
    volumes:
      - ./api/public:/var/www/public:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8080:80
    networks:
      - app-network
  site:
    build:
      context: ./site
    ports:
      - 3000:3000
    networks:
      - app-network
  admin:
    build:
      context: ./admin
    ports:
      - 3001:3001
    networks:
      - app-network
  database:
    image: postgres:13-alpine
    container_name: "database"
    environment:
      POSTGRES_DB: um_api
      POSTGRES_PASSWORD: VQJ2m2RGq3Kw
      POSTGRES_USER: um_api
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    networks:
      - app-network
  redis:
    build:
      context: ./redis
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - app-network

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge