version: "3.9"

services:
  php-fpm:
    build:
      context: api
    restart: unless-stopped
    depends_on:
      - nginx
      - database
    working_dir: /var/www
    environment:
      MERCURE_URL: http://localhost
      MERCURE_PUBLIC_URL: http://localhost
      MERCURE_JWT_SECRET: S3cr3t
    volumes:
      - ./api:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8080:80
    networks:
      - app-network
  site:
    build:
      context: ./site
    ports:
      - 3000:3000
    networks:
      - app-network
  admin:
    build:
      context: ./admin
    ports:
      - 3001:3001
    networks:
      - app-network
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_USER=api-platform
    volumes:
      - db_data:/var/lib/postgresql/data:rw
  redis:
    image: redis:latest

volumes:
  db_data:

networks:
  app-network:
    driver: bridge